version: '3'

services:
  backend:
    container_name: nest_api
    build: nest-api
    ports:
      - '3000:3000'
    environment:
      - MONGO_DSN=mongodb://root:root@db/nest?authSource=admin
    depends_on:
      - db

  frontend:
    container_name: react_frontend
    build: react-frontend
    ports:
      - '3001:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

  db:
    image: mongo:4.4.4
    restart: always
    volumes:
      - .docker/dbdata:/data/db
      - .docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nest
